// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: protos/window.proto

package window

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WindowId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChromiumId *int32 `protobuf:"varint,1,opt,name=chromium_id,json=chromiumId,proto3,oneof" json:"chromium_id,omitempty"`
	GeckoId    *int32 `protobuf:"varint,2,opt,name=gecko_id,json=geckoId,proto3,oneof" json:"gecko_id,omitempty"`
}

func (x *WindowId) Reset() {
	*x = WindowId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_window_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowId) ProtoMessage() {}

func (x *WindowId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_window_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowId.ProtoReflect.Descriptor instead.
func (*WindowId) Descriptor() ([]byte, []int) {
	return file_protos_window_proto_rawDescGZIP(), []int{0}
}

func (x *WindowId) GetChromiumId() int32 {
	if x != nil && x.ChromiumId != nil {
		return *x.ChromiumId
	}
	return 0
}

func (x *WindowId) GetGeckoId() int32 {
	if x != nil && x.GeckoId != nil {
		return *x.GeckoId
	}
	return 0
}

type MainWindowList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Windows []*WindowId `protobuf:"bytes,2,rep,name=windows,proto3" json:"windows,omitempty"`
}

func (x *MainWindowList) Reset() {
	*x = MainWindowList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_window_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MainWindowList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainWindowList) ProtoMessage() {}

func (x *MainWindowList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_window_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainWindowList.ProtoReflect.Descriptor instead.
func (*MainWindowList) Descriptor() ([]byte, []int) {
	return file_protos_window_proto_rawDescGZIP(), []int{1}
}

func (x *MainWindowList) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MainWindowList) GetWindows() []*WindowId {
	if x != nil {
		return x.Windows
	}
	return nil
}

var File_protos_window_proto protoreflect.FileDescriptor

var file_protos_window_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x6e, 0x6b, 0x73, 0x22, 0x6d, 0x0a, 0x08, 0x57,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0b, 0x63, 0x68, 0x72, 0x6f, 0x6d,
	0x69, 0x75, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a,
	0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a,
	0x08, 0x67, 0x65, 0x63, 0x6b, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x01, 0x52, 0x07, 0x67, 0x65, 0x63, 0x6b, 0x6f, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a,
	0x0c, 0x5f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x69, 0x75, 0x6d, 0x5f, 0x69, 0x64, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x67, 0x65, 0x63, 0x6b, 0x6f, 0x5f, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x0e, 0x4d, 0x61,
	0x69, 0x6e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x28, 0x0a, 0x07,
	0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6c, 0x6e, 0x6b, 0x73, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x64, 0x52, 0x07, 0x77,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x32, 0x3c, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x6c, 0x6e, 0x6b, 0x73, 0x2e, 0x4d, 0x61,
	0x69, 0x6e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6c,
	0x6e, 0x6b, 0x73, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_window_proto_rawDescOnce sync.Once
	file_protos_window_proto_rawDescData = file_protos_window_proto_rawDesc
)

func file_protos_window_proto_rawDescGZIP() []byte {
	file_protos_window_proto_rawDescOnce.Do(func() {
		file_protos_window_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_window_proto_rawDescData)
	})
	return file_protos_window_proto_rawDescData
}

var file_protos_window_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_window_proto_goTypes = []interface{}{
	(*WindowId)(nil),       // 0: lnks.WindowId
	(*MainWindowList)(nil), // 1: lnks.MainWindowList
}
var file_protos_window_proto_depIdxs = []int32{
	0, // 0: lnks.MainWindowList.windows:type_name -> lnks.WindowId
	1, // 1: lnks.Test.Send:input_type -> lnks.MainWindowList
	1, // 2: lnks.Test.Send:output_type -> lnks.MainWindowList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_window_proto_init() }
func file_protos_window_proto_init() {
	if File_protos_window_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_window_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_window_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MainWindowList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_window_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_window_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_window_proto_goTypes,
		DependencyIndexes: file_protos_window_proto_depIdxs,
		MessageInfos:      file_protos_window_proto_msgTypes,
	}.Build()
	File_protos_window_proto = out.File
	file_protos_window_proto_rawDesc = nil
	file_protos_window_proto_goTypes = nil
	file_protos_window_proto_depIdxs = nil
}
